version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend_network
networks:
  frontend_network:
    driver: bridge

