name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t frontend .

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key secret here

    - name: Log in to Remote Server
      env:
        SSHPASS: ${{ secrets.SSH_PASS }}
      run: |
        sshpass -p "${SSHPASS}" ssh -o StrictHostKeyChecking=no root@64.225.71.203 "echo 'Logged in successfully!'"

    - name: Pull Latest Code, Stop Containers, and Rebuild Docker Image on Remote Server
      env:
        SSHPASS: ${{ secrets.SSH_PASS }}
      run: |
        # SSH into the remote server to pull the latest changes, stop containers, and rebuild
        sshpass -p "${SSHPASS}" ssh -o StrictHostKeyChecking=no root@64.225.71.203 <<EOF
          # Navigate to the project directory
          cd /HappyPatient/front

          # Pull the latest code from GitHub
          git pull origin main

          # Stop and remove the running Docker containers
          docker-compose down

          # Rebuild the Docker image and start the containers
          docker-compose up --build -d
        EOF
