name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t frontend .

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Log in and Deploy on Remote Server
      env:
        SSH_HOST: root@64.225.71.203
        PROJECT_PATH: /HappyPatient/front
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_HOST <<EOF
          # Navigate to the project directory
          cd /HappyPatient/front

          # Ensure the correct SSH key is used for Git operations
          eval \$(ssh-agent -s)
          ssh-add /root/.ssh/id_ed25519

          # Pull the latest code from GitHub
          git pull origin main

          # Stop and remove the running Docker containers
          docker-compose down

          # Rebuild the Docker image and start the containers
          docker-compose up --build -d
        EOF
